// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByYSdbvyBOjyluyJRwcIUcKDE_E7gGy7E',
    appId: '1:671135823773:web:0a7fa538e8f6d3e005e174',
    messagingSenderId: '671135823773',
    projectId: 'zegotest',
    authDomain: 'zegotest.firebaseapp.com',
    storageBucket: 'zegotest.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS0zb_afo6hxjsRilnrw9ORkMDOkqTds8',
    appId: '1:671135823773:android:612920914139f00005e174',
    messagingSenderId: '671135823773',
    projectId: 'zegotest',
    storageBucket: 'zegotest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjoqwZEwrDhKP_-oCPratAWm7ueyOTIvs',
    appId: '1:671135823773:ios:b4c3d69a356653ec05e174',
    messagingSenderId: '671135823773',
    projectId: 'zegotest',
    storageBucket: 'zegotest.firebasestorage.app',
    iosBundleId: 'com.zegocloud.demo.pkbattles1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjoqwZEwrDhKP_-oCPratAWm7ueyOTIvs',
    appId: '1:671135823773:ios:3572f4cf7df6a49305e174',
    messagingSenderId: '671135823773',
    projectId: 'zegotest',
    storageBucket: 'zegotest.firebasestorage.app',
    iosBundleId: 'com.gobbog.callfrnduser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByYSdbvyBOjyluyJRwcIUcKDE_E7gGy7E',
    appId: '1:671135823773:web:115f2475faede64205e174',
    messagingSenderId: '671135823773',
    projectId: 'zegotest',
    authDomain: 'zegotest.firebaseapp.com',
    storageBucket: 'zegotest.firebasestorage.app',
  );

}